hidden_packages:
  - libreoffice
  - mysql-workbench
  - putty
  - ultrasearch
  - vysor

update_info:
  #google-chrome:
  #  method: uptodown
  #  version_page_url: https://google-chrome.en.uptodown.com/windows
  #  download_page_url: https://google-chrome.en.uptodown.com/windows/download
  microsoft-edge:
    method: uptodown
    version_page_url: https://microsoft-edge.en.uptodown.com/windows
    download_page_url: https://microsoft-edge.en.uptodown.com/windows/download
  firefox:
    method: uptodown
    version_page_url: https://mozilla-firefox.en.uptodown.com/windows
    download_page_url: https://mozilla-firefox.en.uptodown.com/windows/download
  1-password:
    method: uptodown
    version_page_url: https://1password.en.uptodown.com/windows
    download_page_url: https://1password.en.uptodown.com/windows/download
  brave:
    method: uptodown
    version_page_url: https://brave-browser.en.uptodown.com/windows
    download_page_url: https://brave-browser.en.uptodown.com/windows/download
  notepad++:
    method: uptodown
    version_page_url: https://notepad.en.uptodown.com/windows
    download_page_url: https://notepad.en.uptodown.com/windows/download
